{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "k8s-hatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-hatch.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.istio.hostname }}
  gateways:
    - {{ if .Values.istio.gatewayName }}{{ .Values.istio.gatewayName }}{{ else }}{{ include "k8s-hatch.fullname" . }}{{ end }}
  tls:
    - match:
        - port: {{ .Values.istio.port }}
          sniHosts:
            - {{ .Values.istio.hostname }}
      route:
        - destination:
            host: {{ include "k8s-hatch.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
