apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-hatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-hatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "k8s-hatch.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
